NAME: 'complex_twonet2_512_padding0_scale_finetone_all_x0'
MODEL:
    backbone: 'vgg16_bn'   #  'vgg16' or 'vgg16_bn'
    pretrained: True
    loss_balance_weight: True
    loss_weight_list: [1,1,1,1,1,1]
    upsample_layer: 'deconv'  # 'deconv' or 'bilinear', 'github'
    interpolate_mode: 'bilinear'  # 'bilinear' or 'nearest' if upsample_layer=='bilinear'
    freeze_bn: True  # for batchnorm
    freeze_bn_affine: True   # for batchnorm
    init_mode: 'xavier'  # 'Gaussian' or 'xavier'

    loss_func_logits: False # Default: True
    loss_reduce: True  # Default: True
    first_pad: 0  # Default: 34
    
TRAIN: 
    resume: True
    trained_model: '../models/2020-01-06--15-53-09_complex_twonet2_512_padding0_scale_x0'
    if_valid: False
    cache_path: '../caches/'
    save_path: '../models/'
    track: 'complex' # 'simple' or 'complex'
    vgg_weight: 0.1
    input_nc: 1
    output_nc: 2
    ngf: 16
    pad: 0
    thresd: 0.5
    crop_size: 512
    overlap: 256
    update_method: "Adam"  # 'Adam' or 'SGD', 'Adam-sgd', 'meteorshowers', 'github'
    change_sgd_epoch: 6   # only for 'adam-sgd'
    change_sgd_lr: 0.0001     # only for 'adam-sgd'

    nepoch: 30
    total_iters: 600000
    warmup_iters: 0
    base_lr: 0.01
    end_lr: 0.01
    display_freq: 100
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5

    fixed_input: False
    batch_size: 4
    num_workers: 4
    is_cuda: True

    random_seed: 555  # -1 is none
SAVE:
    MAT:
        normalize: True # whether divide the max value
DATA:
    scale_range: 100
    patch_size: 
        - 512
        - 512
    folder_name: '../../data'
    train_data_list: 'data_list/complex_crop_1024_train_all_list.txt'
    valid_data_list: 'data_list/complex_crop_1024_valid_list.txt'
    invalid_border: 50
    
    AUG:
        random_fliplr: True
        random_flipud: True
        random_flipz: True
        random_rotation: True
        color_jitter: True
        COLOR:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
        elastic_trans: False
        ELASTIC:
            alpha_range: 100
            sigma: 10
            shave: 20
        gauss_noise: False
        GAUSS:
            gauss_mean: 0
            gauss_sigma: 0.001

TEST:
    mode: 'test'  # 'train' or 'valid' or 'test'
    crop_way: 'crop_1024'
    model_name: '2020-01-14--16-09-10_complex_twonet2_512_padding0_scale_finetone_all_x0'
    thresd: 0.5
    